### PR TITLE
added keyword table according to #176

### PR DESCRIPTION
**Pull request by arch-dimension**
see issue #176 
I will leave the previous table as is because it contains different information and it is per article.

### CODE REVIEW

**Review by jouwana — CHANGES_REQUESTED** [review]
you have a syntax error (which also means the table wasnt created)
image

and is it possible to add a 'count' section? although i didnt request it before, i think it would be useful information. similar to what we had in the original "articles" table

**Comment by jouwana** [comment]
there is another error you have after fixing the create table function (which i tried on local to see if everything is okay and get  demon).

look at this code here:
image

you are only adding rows, but never summing up intonation of words that already exist in the query, example:
image

another error i noticed is that a keyword we sent as part of the query is was added with both neutral and positive intonation:
image

as it is a keyword we sent, it should always have the intonation we send with it.

**Comment by arch-dimension** [comment]
> another error i noticed is that a keyword we sent as part of the query is was added with both neutral and positive intonation: in this case it is the word 'בנייה' image
> 
> as it is a keyword we sent, it should always have the intonation we send with it.
The reason for this is because the key is (keyword,intonation,website)  as requested so its allowed, if you want it changed we can just alter the primary key constraints of the table

**Comment by jouwana** [comment]
> 
> 


> > as it is a keyword we sent, it should always have the intonation we send with it.
> 
> The reason for this is because the key is (keyword,intonation,website)  as requested so its allowed, if you want it changed we can just alter the primary key constraints of the table
> 
> 
> 

The is not what i meant.
'בנייה' is a word we currently have saved in our keyword/intonation dataset (which we should turn off after, we shouldnt save anymore , but this could be the same problem for words sent in advanced search with negative or positive int)
We said we will always prioritize the intonation that the user gave us, so everytime watson finds something about the word itself, or we find it, it should have the intonation the user gave us.
Does that make more sense?
I do want the ability that intonationless keywords and other watson found to have different intonations in the DB, thats good for the graphs, but not for the words they gave us to be in "positive" or "negative" intonation of advanced search

**Review by jouwana — APPROVED** [review]

**Pull request merged**
