### PR TITLE
Feature articles sentiment score table

### PR DESCRIPTION
**Pull request by arch-dimension**
added the following:
1. extraction of keywords in a sentence (using the language understanding module)
2. extraction of keywords sentiment and score
3. added sentiment analysis generation in a separate table- the article, the overall sentiment, the positive keyword sum (if any), the negative keyword sum, and the date.
4. did not add the UI to show the results,I am leaving it up to the front-end.

### CODE REVIEW

**Comment by jouwana** [comment]
@arch-dimension could you show an example of what the data in the database looks like?
and is it possible for you to create the route in the 'server'? similar to the route that calls for all data, but one that only reads from the new table you added.

**Comment by arch-dimension** [comment]
I added a test in ArticleTest to show the format of the rows

**Comment by arch-dimension** [comment]
I can create a route, but to handle concurrent requests, I need table_id as a parameter

**Comment by arch-dimension** [comment]
@jouwana  I added a new route in index.ts, but I need you to look it over to make sure the format is acceptable, what you do with the data is up to you.

**Comment by jouwana** [comment]
> I added a test in ArticleTest to show the format of the rows

I meant more like add a picture or general info into the pull request
But its fine, ill just look it over when i try to add the rest in

**Comment by jouwana** [comment]
> @jouwana  I added a new route in index.ts, but I need you to look it over to make sure the format is acceptable, what you do with the data is up to you.

We cant sent a "body" in the "get" request, we will need to send the table id as a parameter in the request url

But I will deal with it later, its okay the rest seems okay

@arch-dimension So you can merge if you want

**Comment by arch-dimension** [comment]
It's a post request not get

**Comment by jouwana** [comment]
> It's a post request not get

I meant the server's app.get("/sentiment") not the one for the API
But its not a problem, ill change it later

**Pull request merged**
